[workspace]
resolver = "3"
members = [
    "crates/assets",
    "crates/bar",
    "crates/compositor",
    "crates/macros",
    "crates/shell"
]
default-members = ["crates/shell"]

[workspace.dependencies]
assets = { path = "crates/assets" }

bar = { path = "crates/bar" }
compositor = { path = "crates/compositor" }
macros = { path = "crates/macros" }

anyhow = "1.0.102"
smallvec = "1.15.1"

gpui = { git = "https://github.com/zed-industries/zed.git", features = ["wayland"] }
gpui_platform = { git = "https://github.com/zed-industries/zed.git", features=[
    "font-kit",
    "wayland",
]}

gpui-component = { git = "https://github.com/longbridge/gpui-component.git" }
